name: My Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set environment variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
          echo "STRING=ESTOU-NA-DEV" >> $GITHUB_OUTPUT
          echo "TEST_ENV=staging" >> $GITHUB_OUTPUT
        elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "STRING=ESTOU-NA-MAIN" >> $GITHUB_OUTPUT
          echo "TEST_ENV=production" >> $GITHUB_OUTPUT
        fi
        
    - name: Echo My Stuff
      run: |
        echo ${{ env.STRING }}
        echo ${{ env.TEST_ENV }}
  another-job:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Echo My Stuff
      run: |
        echo ${{ env.STRING }}
        echo ${{ env.TEST_ENV }}